try:
    # noinspection PyUnresolvedReferences
    import ms.version
except ImportError:
    pass
else:
    # ms.version.addpkg('mock', '1.0.1')
    # ms.version.addpkg('setuptools', '0.6c11')
    # ms.version.addpkg('protobuf', '3.6.1')
    # ms.version.addpkg('zope.interface', '4.5.0')
    # ms.version.addpkg('twisted', '12.0.0')
    # ms.version.addpkg('coverage', '3.6')
    # ms.version.addpkg('ipaddress', '1.0.6')
    # ms.version.addpkg('mako', '0.7.2')
    # ms.version.addpkg('cdb', '0.34')
    # ms.version.addpkg('six', '1.9.0')
    # ms.version.addpkg('jsonschema', '2.3.0')
    # ms.version.addpkg('sqlalchemy', '1.0.11')
    # ms.version.addpkg('psycopg2-binary', '2.8.3')
    # ms.version.addpkg('ms.modulecmd', '1.0.4')
    # ms.version.addpkg('dateutil', '1.5')
    # ms.version.addpkg('cdb', '0.34')

    ms.version.addpkg("mock", "3.0.5")
    ms.version.addpkg("setuptools", "45.0.0")
    ms.version.addpkg("zope.interface", "4.6.0")
    ms.version.addpkg("sqlalchemy", "1.3.23")
    ms.version.addpkg("psycopg2", "2.8.5-11.4.0-py37")
    ms.version.addpkg("ms.modulecmd", "1.1.1")
    ms.version.addpkg("ipaddress", "1.0.23")
    ms.version.addpkg("dateutil", "2.8.1")
    ms.version.addpkg("pure-cdb", "3.1.0")
    ms.version.addpkg("six", "1.16.0")
    ms.version.addpkg("jsonschema", "3.2.0")
    ms.version.addpkg("importlib-metadata", "4.9.0")
    ms.version.addpkg("zipp", "3.0.0")
    ms.version.addpkg("typing-extensions", "3.7.4.3")
    ms.version.addpkg("pbr", "5.4.4")
    ms.version.addpkg("prettytable", "1.0.1")
    ms.version.addpkg("attrs", "20.3.0")
    ms.version.addpkg("pyrsistent", "0.15.7-py37")
    ms.version.addpkg("twisted", "21.2.0")
    ms.version.addpkg("incremental", "16.10.1")
    ms.version.addpkg("Automat", "20.2.0")
    ms.version.addpkg("hyperlink", "20.0.1")
    ms.version.addpkg("idna", "3.2")
    ms.version.addpkg("importlib-metadata", "4.9.0")
    ms.version.addpkg("zipp", "3.0.0")
    ms.version.addpkg("typing-extensions", "3.7.4.3")
    ms.version.addpkg("pbr", "5.4.4")
    ms.version.addpkg("prettytable", "1.0.1")
    ms.version.addpkg("constantly", "15.1.0")
    ms.version.addpkg("coverage", "5.3.1-py37")
    ms.version.addpkg("ipaddress", "1.0.23")
    ms.version.addpkg("mako", "1.0.7")
    ms.version.addpkg("pure-cdb", "3.1.0")
    ms.version.addpkg("six", "1.15.0")
    ms.version.addpkg("jsonschema", "3.2.0")
    ms.version.addpkg("attrs", "20.3.0")
    ms.version.addpkg("pyrsistent", "0.15.7-py37")
    ms.version.addpkg("protobuf", "3.17.3")
    # ms.version.addpkg('protobuf', '3.10.0')
