default_language_version:
    python: python3.10
repos:
-   repo: local
    # Local to not query github to get modules and use local settings instead of pre-commit one.
    hooks:
    - id: darker
      name: darker
      entry: /ms/dist/python/PROJ/darker/1.7.2/bin/darker
      language: system
      types: [ python ]
    - id: ruff
      name: ruff
      entry: /ms/dist/python/PROJ/ruff/0.4.2/bin/ruff
      args: ['check', '--fix', '--exit-non-zero-on-fix']
      language: system
      types: [python]
