language: python

train_version: 1.0

tools:
   - msde/git/2.35.3
   - python/core/3.7.9
   - msde/msdlbuild/prod
   - perl5/core/5.26.1

test_setup: &test_setup
  - mkdir -p ../install/common/test-results/UNIT/xml/ ../install/common/test-results/INTEGRATION/coveragepy/xml/

build_types:
   - build_type:
          name: release
          build:
          - script: git ls-remote --sort='version:refname' --tags /ms/dev/aquilon/aqd/SCM/aqd.git | grep refs/tags/TRAIN_DIST_aquilon/aqd | tail -n 2 | head -n 1 | awk '{print $2}' | sed 's/^\([^/]\+\/\)\{2\}//' > doc/version.txt
          - script: msdlbuild clean
          - script: make clean
          - script: make install
          - script: msdlbuild metadata

test_types:
  - test_type:
        name: unit
        test: set -o pipefail; ./tests/runtests.py --config=./tests/unittest.conf --no-interactive -x integration | tee ./tests/aqdtests.log
  - test_type:
         name: all
         test: set -o pipefail; ./tests/runtests.py --config=./tests/unittest.conf --no-interactive | tee ./tests/aqdtests.log
  - test_type:
       name: failfast
       test: which python; set -o pipefail; python tests/runtests.py --config=tests/unittest.conf --failfast --no-interactive --coverage --verbose | tee tests/aqdtests.log
  - test_type:
       name: restart
       test: ./tests/restarttests.sh
  - test_type:
       name: infoblox-end-to-end
       test: set -o pipefail; AQDCONF=tests/ib-end-to-end.conf ./tests/runtests.py --infoblox-integration --no-interactive --config=tests/ib-end-to-end.conf --failfast | tee ./tests/aqdtests.log
  - test_type:
      name: lint
      test:
        - script:
            command:  # Do not fail build on error, for now.
              - *test_setup
              - echo -e "\n-- ruff linter check --"
              - /ms/dist/python/PROJ/ruff/0.0.289-py37/bin/ruff check --config pyproject.toml . && /ms/dist/python/PROJ/ruff/0.0.289-py37/bin/ruff check --config pyproject.toml --format junit -o ../install/common/test-results/ruff.xml .
              - echo -e "\n** ruff is currently informative only, but try to fix issues when possible. Try 'ruff --check --fix' on your file for quick wins.**".
              - echo -e "\n-- black (darker) code reformatter on commit check --"
              - tools/darker --diff --check --revision $(git rev-parse --abbrev-ref --symbolic-full-name @{u}) || echo -e "\nFAILED - !!! darker found formating issue. Please run **black** or *tools/darker** on new code to fix and resubmit code. !!!\n"
  - test_type:
      name: jenkins
      test:
      - script:
          command:
            - *test_setup
            - AQDCONF=tests/unittest.conf python test/test_xmlrunner.py
            - ./tests/jenkinstest.sh
            - cp tests/aqdtests.log ../install/common/test-results/aqdtests.log
            - cp -R /var/tmp/$USER/run/quattor/logs/ ../install/common/test-results/quattor-logs
            - cp ../install/common/test-results/quattor-logs/coverage/aqd.xml ../install/common/test-results/INTEGRATION/coveragepy/xml/coverage-test.xml
            - cp ../install/common/test-results/UNIT/xml/test.xml ../install/common/test-results/INTEGRATION/coveragepy/xml/
