#!/usr/bin/env python
# This is a updated copy of /ms/dist/python/PROJ/darker/1.7.2/bin/darker
# With updated ms dependencies for Python 3.7

# Darker is a code formatter using black, isort and flynt, but only on new code and not whole file/tree.
# This won't reformat the whole project, so we should run it on every PR now.

# MSVERSION PATCH
import ms.version

_DEPENDENCIES = [
# darker==1.7.2
("python", "darker", "1.7.2"),
# black==23.1.0"
("python", "black", "23.1.0"),
# click==8.1.3
("python", "click", "8.1.3"),
# importlib-metadata==6.6.0
("python", "importlib-metadata", "6.6.0"),
# mypy-extensions==1.0.0
("python", "mypy_extensions", "1.0.0"),
# packaging==23.1
("python", "packaging", "23.1"),
# pathspec==0.11.1
("python", "pathspec", "0.11.1"),
# platformdirs==3.8.0
("python", "platformdirs", "3.8.0"),
# setuptools==65.5.1
("python", "setuptools", "65.5.1"),
# toml==0.10.2
("python", "toml", "0.10.2"),
# tomli==2.0.1
("python", "tomli", "2.0.1"),
# typed-ast==1.5.4
("python", "typed-ast", "1.4.3"),
# typing-extensions==4.7.0
("python", "typing-extensions", "4.7.0"),
# zipp==3.15.0
("python", "zipp", "3.15.0"),
# isort==5.11.5
("python", "isort", "5.11.5"),
# astor==0.8.1
("python", "astor", "0.8.1"),
# setuptools==65.5.1
("python", "setuptools", "65.5.1"),
# tomli==2.0.1
("python", "tomli", "2.0.1"),
# flynt==0.77
("python", "flynt", "0.77"),
]

def _ADDPKGS():
    for (m, p, r) in _DEPENDENCIES:
        try:
            ms.version.addpkg(p, r, meta=m)
        except ms.version.MSVersionError:
            ms.version.addpkg(p, r, "dev", meta=m)

_ADDPKGS()
del _ADDPKGS



# for the possible issue in case you've already loaded pkg_resources
# see https://stackoverflow.com/questions/26786680
import sys

if ("pkg_resources" in sys.modules):
    import pkg_resources
    if hasattr(pkg_resources, "_initialize_master_working_set"):
        pkg_resources._initialize_master_working_set()
# MSVERSION PATCH
import re
import sys

from darker.__main__ import main_with_error_handling

if __name__ == "__main__":
    sys.argv[0] = re.sub(r"(-script\.pyw?|\.exe)?$", "", sys.argv[0])
    sys.exit(main_with_error_handling())

