CREATE TABLE "SUBSCRIPTION" (
       "RESOURCE_ID" NUMBER(*,0) CONSTRAINT "SUBSCRIPTION_RESOURCE_ID_NN" NOT NULL ENABLE,
       "CONFIGMODE" VARCHAR2(32 CHAR) CONSTRAINT "SUBSCRIPTION_CONFIGMODE_NN" NOT NULL ENABLE,
       "USERNAME" VARCHAR2(255 CHAR) CONSTRAINT "SUBSCRIPTION_USERNAME_NN" NOT NULL ENABLE,
       "SUBSCRIPTION" VARCHAR2(255 CHAR) CONSTRAINT "SUBSCRIPTION_SUBSCRIPTION_NN" NOT NULL ENABLE,
       CONSTRAINT "SUBSCRIPTION_PK" PRIMARY KEY ("RESOURCE_ID") ENABLE,
       CONSTRAINT "SUBSCRIPTION_RESOURCE_FK" FOREIGN KEY ("RESOURCE_ID") REFERENCES "resource" ("ID") ON DELETE CASCADE ENABLE,
       CONSTRAINT "SUBSCRIPTION_USERINFO_FK" FOREIGN KEY ("USERNAME") REFERENCES "USERINFO" ("NAME") ENABLE
);
QUIT;
